#ifndef LIBRARY_STORE_ENUMS_H
#define LIBRARY_STORE_ENUMS_H

enum class MenuOption {
    ADD_MEMBER = 1,
    MANAGE_BOOK = 2,
    DISPLAY_BOOKS_BORROWED = 3,
    END_SESSION = 4
};

#endif //LIBRARY_STORE_ENUMS_H
